### ISSUE TITLE
Re-identification bounty / challenge

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/QUIPP-collab#106]
Email from UKAN Discussion list on Data Anonymisation <UKAN@JISCMAIL.AC.UK>
>Hi All,
>
>I'm pleased to announce a bounty program for attacking the data anonymization mechanism Diffix Dogwood, developed at MPI-SWS in research partnership with Aircloak.
>
>This is a unique bounty program geared towards trying to re-identify anonymized data. Basic idea:
>
>* we provide an interface to Diffix (and full documentation ... it is white-box)
>* participant attacks by sending queries ... tries to single-out individuals in the datasets behind Diffix
>* we measure success rate (basically measure of accuracy of statements about the data)
>* we pay according to how much is learned, how accurately it was learned, and how much prior knowledge was needed to learn it.
>
>The bounty program is sponsored by MPI-SWS, with a purse of $30K and a top prize of $10K.
>
>If you are interested you can learn more at https://www.gda-score.org/mpi-sws-diffix-challenge-2020/.
>
>Paul Francis
>Director MPI-SWS
>Co-founder Aircloak

**Comment by ots22** [comment]
This closes very soon (26 Nov).  The challenge web page links to some interesting resources that might be worth looking at in more detail, so moving this issue to 'For Review' before we close it.
