### ISSUE TITLE
Add dython to docker image

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/QUIPP-collab#111]
The library dython is used to calculate correlation utility metrics. It needs to be added to the docker image.

**Comment by gmingas** [comment]
@LouiseABowler I am trying to add the `dython` library to the docker image using the instructions [here]() but getting the following error and I was wandering if you encountered before. I looked a bit online and couldn't find a solution but will keep looking tomorrow more carefully.

> Step 35/76 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
 ---> Running in d2c4378320a2
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.CPTrl346TN/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
gpg: keyserver receive failed: Cannot assign requested address
Removing intermediate container d2c4378320a2
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9' returned a non-zero code: 2

**Comment by gmingas** [comment]
Ignore the above, it seems it had to do with my internet connection.

**Comment by gmingas** [comment]
@LouiseABowler I have now created the image locally and trying to push it with (following the instructions written [here](https://github.com/alan-turing-institute/QUIPP-pipeline/tree/develop/env-configuration)):
> docker push turinginst/quipp-env:0.0.4

But I get the following error:
> denied: requested access to the resource is denied

Do I need to login with different credentials to push to turinginst? I tried to tag the image as suggested in some stackoverflow comments but it did not work.

**Comment by LouiseABowler** [comment]
You'll need to be a member of the turinginst Docker organisation to push an image there - @sgibson91, do you have admin rights and would you be able to add @gmingas please?

**Comment by sgibson91** [comment]
I've sent an invite to your Turing address @gmingas :)

**Comment by gmingas** [comment]
Thanks @sgibson91 , it works now.

**Comment by gmingas** [comment]
The image has been updated to contain dython, it is version 0.0.4 seen [here](https://hub.docker.com/r/turinginst/quipp-env/tags?page=1&ordering=last_updated). Closing this.
