### ISSUE TITLE
Identify and implement a second DP synthesis method

### ISSUE THREAD

**Issue by ots22** [alan-turing-institute/QUIPP-collab#145]
E.g. Privbayes
https://github.com/kasra-hosseini/synthetic_data_release/blob/master/generative_models/data_synthesiser.py

**Comment by ots22** [comment]
#143?

**Comment by gmingas** [comment]
Adding PrivBayes to the pipeline, WIP in [this](https://github.com/alan-turing-institute/QUIPP-pipeline/tree/feature/145-add-privbayes) branch

**Comment by gmingas** [comment]
Notebook with some initial results, when forcing PrivBayes to use the same Bayesian Network structure in every run to avoid random structures [here](https://github.com/alan-turing-institute/QUIPP-pipeline/blob/2635448b55f96e1a1ecc50bd69944f5fc38e6c64/examples/privacy_utility_tradeoff/exp_privbayes/epsilon_vs_utility.ipynb)
