### ISSUE TITLE
Write Synthetic Data section for Privacy Preserving Computation paper

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/QUIPP-collab#47]
## Resources
- NHS Information Governance Toolkit - Requirements for Secondary Use Organisations ([original](https://www.igt.hscic.gov.uk/RequirementsList.aspx?tk=438094922126103&lnv=2&cb=48617f77-6463-4962-a793-2c4c2c4a19c3&sViewOrgType=19&sDesc=Secondary+Use+Organisation) | [zotero](https://www.zotero.org/groups/2386186/syntheticdata/items/itemKey/JTTRVBRP))

**Comment by gmingas** [comment]
@ots22 is this still relevant?

**Comment by ots22** [comment]
Perhaps not - @vollmersj?

**Comment by ots22** [comment]
Closing this (abandoned - please reopen if I'm mistaken)
