### ISSUE TITLE
Build a privacy metric

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/QUIPP-collab#60]

**Comment by gmingas** [comment]
Looking again at this discussion while writing the report. I was thinking that a possible third-way approach (in addition to the data-driven and method-specific ones) would be to exclusively use inherently differentially private synthesis methods. (GANs, VAEs, multiple imputation with embedded DP assuming we can find those and possibly the version of plausibly deniability that is equivalent to DP). 

If we do this, we would not need a data-driven method; all of the methods would have the same privacy metric (epsilon), which would allow us to compare them directly. Unless I am missing something and epsilon is not equivalent across methods..

**Comment by ots22** [comment]
See #123 (Privacy vs utility for differentially private methods).

In the pipeline, a privacy metric applied to these methods could just report the computed or provided privacy parameters where applicable.

**Comment by ots22** [comment]
Closing this - some of the discussion above to be captured in the report (#112).
