### ISSUE TITLE
Whitaker lab meeting with Ed Palmer (6th Feb)

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/QUIPP-collab#64]
Kirstie has invited Ed Palmer, one of the new SSI fellows, to her lab meeting on Thursday 6th February. Ed is doing some work on synthetic data so Kirstie has said that the QUiPP team is welcome to come along if we're interested.

Lab meeting runs 3-4pm (with the option to stay later), room ~TBC~ David Blackwell.

Ed's profile is [here](https://www.software.ac.uk/about/fellows/edward-palmer) - not much about his synthetic data work, we heard about that via Sarah from one of the fellows' meetings.

If you're planning to come, can you please put a 😄 emoji on this message so I can make sure we get a big enough room? If there are lots of us, it might be better to set up a separate meeting with Ed earlier that day rather than overfill the usual lab meeting.

**Comment by ots22** [comment]
Notes in the comment above now in 'meeting-notes'
Issue #136 for further discussion on this dataset

Closing
