### ISSUE TITLE
Inviting collaborators to planning meetings

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/QUIPP-collab#69]
Further to #24 (inviting collaborators to this repo), we discussed inviting collaborators to the planning meetings with @niklomax, @gmingas, @crangelsmith, @martintoreilly at the 10 Feb 2020 meeting. We discussed the following.

- At what point is it useful for an external collaborator to start attending? Suggest once we've taken concrete collaboration steps - e.g. received some data, signed a data sharing agreement, done some initial analysis

- How frequently should external collaborators attend? Suggest one meeting per month has full set of collaborators, with a focus on external collaboration, with the weekly meetings in between more focussed on internal project planning.

Thoughts @geoalison, @nickmalleson, @vollmersj, @LouiseABowler, @ots22, @kasra-hosseini ?

**Comment by ots22** [comment]
Noting tacit agreement with the above plan.  Closing for now.
