### ISSUE TITLE
Contribute to working paper (consolidate our understanding so far - e.g. privacy)

### ISSUE THREAD

**Issue by ots22** [alan-turing-institute/QUIPP-collab#94]

**Comment by vollmersj** [comment]
where is the most recent version

**Comment by ots22** [comment]
It's "QUiPP Paper Outline" on Overleaf

**Comment by gmingas** [comment]
@ots22 @vollmersj Is there a link to the overleaf document? If we already have something written we could recycle parts of it for the summary report we want to compile

**Comment by martintoreilly** [comment]
https://www.overleaf.com/project/5e59251dd98d92000148c704

**Comment by martintoreilly** [comment]
@ots22 You're the only owner, can you give the whole team access. Any reason we shouldn't all be owners on project papers?

**Comment by ots22** [comment]
Added Greg and Nick.

There can be only one owner, but very happy for it not to be me (at least for the time being).

**Comment by martintoreilly** [comment]
Is owner the only role with rights to invite others?

**Comment by ots22** [comment]
Yes it looks like it.

**Comment by ots22** [comment]
Suggest we abandon this issue in favour of #112 - but keep the Overleaf document ready for #102.
